train_csv: "./dataset/train.csv"
val_csv: "./dataset/val.csv"
train_dir: "./dataset/train"
val_dir: "./dataset/val"
batch_size: 32
num_workers: 4
max_epochs: 20
max_lr: 0.001
use_amp: true
use_fpn: true
fpn_size: 256
use_selection: true
num_classes: 30
num_selects:
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: true
lambda_b0: 0.5
lambda_s: 1.0
lambda_n: 1.0
lambda_b: 1.0
lambda_c: 1.0
update_freq: 1
log_freq: 10
temperature: 1.0
eval_freq: 5
pretrained: null
save_dir: "./herbs_checkpoints"
use_wandb: false
wandb_entity: "herbs"
project_name: "herbs"
exp_name: "baseline"
